# Generated by Django 5.1.6 on 2025-02-26 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField()),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('menu_reservado', models.JSONField()),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='procesar_pdfs.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('primero', 'Primer Plato'), ('segundo', 'Segundo Plato'), ('postre', 'Postre')], max_length=10)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='procesar_pdfs.restaurante')),
            ],
        ),
    ]
