# Generated by Django 5.1.6 on 2025-02-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesar_pdfs', '0002_remove_reserva_restaurante_customuser_delete_plato_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
